class HomepageLocators:
    close_bottom_pop_up = '//*[@id="onetrust-close-btn-container"]/button'
    banner_cta = '//*[@id="__next"]/main/div[1]/div/div/div/a/button'
    banner_header_text = '//*[@id="__next"]/main/div[1]/div/div/div/h1'
    banner_sub_copy_text = '//*[@id="__next"]/main/div[1]/div/div/div/p'
    banner_image_locators = '//*[@id="__next"]/main/div[1]/div/img'
    shop_by_collection_section = '//*[@id="__next"]/main/div[2]'
    section_header_text = '//*[@id="__next"]/main/div[2]/div[1]/h2'
    see_all_product_cta = '//*[@id="__next"]/main/div[2]/div[1]/a/button'
    collection_image1 = '//*[@id="__next"]/main/div[2]/div[2]/div[1]/div[1]/a/img'
    daily_moisture_details_header_text = '//*[@id="__next"]/main/div[2]/div[2]/div[1]/div[2]/a'
    daily_moisture_details_sub_text = '//*[@id="__next"]/main/div[2]/div[2]/div[1]/div[3]'
    daily_moisture_cta = '//*[@id="__next"]/main/div[2]/div[2]/div[1]/a/button'
    collection_image2 = '//*[@id="__next"]/main/div[2]/div[2]/div[2]/div[1]/a/img'
    advanced_therapy_header_text = '//*[@id="__next"]/main/div[2]/div[2]/div[2]/div[2]/a'
    advanced_therapy_sub_text = '//*[@id="__next"]/main/div[2]/div[2]/div[2]/div[3]'
    advanced_therapy_cta = '//*[@id="__next"]/main/div[2]/div[2]/div[2]/a/button'
    collection_image3 = '//*[@id="__next"]/main/div[2]/div[2]/div[3]/div[1]/a/img'
    intense_skin_repair_header_text = '//*[@id="__next"]/main/div[2]/div[2]/div[3]/div[2]/a'
    intense_skin_repair_sub_text = '//*[@id="__next"]/main/div[2]/div[2]/div[3]/div[3]'
    intense_skin_repair_cta = '//*[@id="__next"]/main/div[2]/div[2]/div[3]/a/button'
    video_section = '//*[@id="__next"]/main/div[3]'
    video = '//*[@id="__next"]/main/div[3]/div'
    about_lubriderm_header_text = '//*[@id="__next"]/main/div[4]/div/h2'
    about_lubriderm_sub_text = '//*[@id="__next"]/main/div[4]/div/p'
    about_us_cta = '//*[@id="__next"]/main/div[4]/div/a'
    our_best_seller = '//*[@id="__next"]/main/div[5]/h2'
    our_best_seller_header_text = '//*[@id="__next"]/main/div[5]/h2/span'
    product1_card_image = '//*[@id="__next"]/main/div[5]/div[1]/div/div/div/div/div[1]/div/div/div[1]/a/img'
    product1_card_name = '//*[@id="__next"]/main/div[5]/div[1]/div/div/div/div/div[1]/div/div/div[2]/a/span'
    buy_now_cta1 = '//*[@id="__next"]/main/div[5]/div[1]/div/div/div/div/div[1]/div/div/div[3]/div[2]/div'
    price_spider_pop_up1 = "body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div"
    price_spider_pop_up1_close = "body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div > span"
    product2_card_image = '//*[@id="__next"]/main/div[5]/div[1]/div/div/div/div/div[2]/div/div/div[1]/a/img'
    product2_card_name = '//*[@id="__next"]/main/div[5]/div[1]/div/div/div/div/div[2]/div/div/div[2]/a/span'
    buy_now_cta2 = '//*[@id="__next"]/main/div[5]/div[1]/div/div/div/div/div[2]/div/div/div[3]/div[2]/div'
    price_spider_pop_up2 = "body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div"
    price_spider_pop_up2_close = "body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div > span"
    product3_card_image = '//*[@id="__next"]/main/div[5]/div[1]/div/div/div/div/div[3]/div/div/div[1]/a/img'
    product3_card_name = '//*[@id="__next"]/main/div[5]/div[1]/div/div/div/div/div[3]/div/div/div[2]/a/span'
    buy_now_cta3 = '//*[@id="__next"]/main/div[5]/div[1]/div/div/div/div/div[3]/div/div/div[3]/div[2]/div'
    price_spider_pop_up3 = "body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div"
    price_spider_pop_up3_close = "body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div > span"
