class HomepageLocators:
    close_bottom_pop_up = '//*[@id="onetrust-close-btn-container"]/button'
    banner_cta = '//*[@id="__next"]/main/div[1]/div/div/div/a/button'
    banner_header_text = '//*[@id="__next"]/main/div[1]/div/div/div/h1'
    banner_sub_copy_text = '//*[@id="__next"]/main/div[1]/div/div/div/p'
    banner_image_locators = '//*[@id="__next"]/main/div[1]/div/img'
    shop_by_collection_section = '//*[@id="__next"]/main/div[2]'
    section_header_text = '//*[@id="__next"]/main/div[2]/div[1]/h2'
    see_all_product_cta = '//*[@id="__next"]/main/div[2]/div[1]/a/button'
    collection_image1 = '//*[@id="__next"]/main/div[2]/div[2]/div[1]/div[1]/a/img'
    daily_moisture_details_header_text = '//*[@id="__next"]/main/div[2]/div[2]/div[1]/div[2]/a'
    daily_moisture_details_sub_text = '//*[@id="__next"]/main/div[2]/div[2]/div[1]/div[3]'
    daily_moisture_cta = '//*[@id="__next"]/main/div[2]/div[2]/div[1]/a/button'
